### ISSUE TITLE
Configuration doesn't work correctly with clang on Linux

### ISSUE THREAD

**Issue by mojca** [boostorg/config#455]
I seem to have troubles using `config` with `clang++-14` on Ubuntu 22.04 running Boost 1.80.0:
* `BOOST_NO_CXX98_FUNCTION_BASE` is not defined
* `BOOST_LIBSTDCXX_VERSION` is too low

See: https://github.com/boostorg/container_hash/issues/22#issuecomment-1312526022

**Comment by pdimov** [comment]
Maybe we should use `_GLIBCXX_RELEASE` when defined under Clang, instead of `__has_include`.

"_GLIBCXX_RELEASE

The major release number for libstdc++. This macro is defined to the GCC major version that the libstdc++ headers belong to, as an integer constant. When compiling with GCC it has the same value as GCC's pre-defined macro __GNUC__. This macro can be used when libstdc++ is used with a non-GNU compiler where __GNUC__ is not defined, or has a different value that doesn't correspond to the libstdc++ version. This macro first appeared in the GCC 7.1 release and is not defined for GCC 6.x or older releases."

**Comment by jzmaddock** [comment]
Cool, I had no idea they had added that macro, and yes using that when present looks good.

@mojca can you investigate why `__has_include(<expected>)` is failing?

**Comment by mojca** [comment]
> @mojca can you investigate why `__has_include(<expected>)` is failing?

Hmmm ... it actually works.

I guess that must be the reason: https://github.com/boostorg/config/pull/445

It was added in August and it hasn't been released in Boost 1.80.0 yet.

Though it's still not clear to me why `BOOST_LIBSTDCXX_VERSION` needs to be checked rather than just the C++ standard.

Also, `_GLIBCXX_RELEASE` returns 12 and that seems like a lot more reliable and robust way to check for the libstdc++ version compared to the other hacks checking for headers.

**Comment by mojca** [comment]
A similar problem for `libc++`.

The source code currently says:
```c++
#if _LIBCPP_VERSION >= 15000
//
// Unary function is now deprecated in C++11 and later:
//
#if __cplusplus >= 201103L
#define BOOST_NO_CXX98_FUNCTION_BASE
#endif
#endif
```
but my `_LIBCPP_VERSION` return 14000 which is smaller and I'll run into the exact same issue with libc++.

**Comment by mojca** [comment]
I tested it now though and it seems that libc++ 14 in fact doesn't complain about the deprecated function (even if it technically is).
